DROP TABLE IF EXISTS
users
,clients
,categories
,products
CASCADE;

CREATE TABLE Users (
	user_id VARCHAR(15) PRIMARY KEY
	,user_email VARCHAR(100) UNIQUE NOT NULL
	,user_name VARCHAR(100) NOT NULL
	,user_lastname VARCHAR(100)
	,user_rol CHAR DEFAULT 'c'
	,created TIMESTAMP NOT NULL
	,updated TIMESTAMP NOT NULL
);

CREATE TABLE Clients (
	client_id VARCHAR(15)
	,client_address VARCHAR(150)
	,FOREIGN KEY (client_id) REFERENCES Users(user_id)
);

CREATE TABLE Categories (
	category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
	,category_name VARCHAR(150) NOT NULL
	,created TIMESTAMP NOT NULL
	,updated TIMESTAMP NOT NULL
);

CREATE TABLE Products (
	product_id VARCHAR(50) NOT NULL
	,product_name VARCHAR(150)NOT NULL
	,product_quantity INTEGER NOT NULL
	,product_price FLOAT NOT NULL
	,product_category INTEGER
	,FOREIGN KEY (product_category) REFERENCES Categories(category_id)
);